source 'https://rubygems.org'

gem 'activerecord', '~> 4.1.16'
gem 'sinatra-activerecord', '~> 2.0.11'
gem 'haveapi', '~> 0.9.0'

# Enable needed database adapters
# gem 'pg'
# gem 'mysql2'
gem 'sqlite3'

# Used to recursively require resources and models
gem 'require_all'

# Password hashing algorithm
gem 'bcrypt'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
