source 'https://rubygems.org'

gem 'activerecord', '~> 7.0.8'
gem 'haveapi', '~> 0.17.0'
gem 'sinatra-activerecord', '~> 2.0.26'

# Enable needed database adapters
# gem 'pg'
# gem 'mysql2'
gem 'sqlite3'

# Used to recursively require resources and models
gem 'require_all'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
