source 'https://rubygems.org'

gem 'activerecord', '~> 7.0.8'
gem 'sinatra-activerecord', '~> 2.0.26'
gem 'haveapi', '~> 0.18.2', path: '../../../../servers/ruby'
gem 'rake'

# Enable needed database adapters
# gem 'pg'
# gem 'mysql2'
gem 'sqlite3', '~> 1.6.6'

# Used to recursively require resources and models
gem 'require_all'

# Password hashing algorithm
gem 'bcrypt'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
