source 'https://rubygems.org'

gem 'activerecord', '~> 8.1.0'
gem 'haveapi', '~> 0.27.1', path: '../../../../servers/ruby'
gem 'rake'
gem 'sinatra-activerecord', '~> 2.0.26'

# Enable needed database adapters
# gem 'pg'
# gem 'mysql2'
gem 'sqlite3'

# Used to recursively require resources and models
gem 'require_all'

# Password hashing algorithm
gem 'bcrypt'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
