source 'https://rubygems.org'
gemspec

gem 'haveapi-client', path: '../../clients/ruby'

group :test do
  gem 'rack-test'
  gem 'rspec'
end

group :activerecord do
  gem 'activerecord', '>= 6.0'
  gem 'sinatra-activerecord'
end
