source 'https://rubygems.org'
gemspec

gem 'haveapi-client', path: '../../clients/ruby'

group :test do
  gem 'rack-test'
  gem 'rackup'
  gem 'rspec'
  gem 'rubocop', '~> 1.85.0', require: false
  gem 'rubocop-rspec', require: false
  gem 'webrick'

  # ActiveRecord adapter specs (always run)
  gem 'activerecord', '>= 8.0'
  gem 'sinatra-activerecord'
  gem 'sqlite3'
end
