source 'https://rubygems.org'
gemspec

gem 'haveapi-client', path: '../../clients/ruby'

group :test do
  gem 'rack-test'
  gem 'rspec'

  # ActiveRecord adapter specs (always run)
  gem 'activerecord', '>= 8.0'
  gem 'sinatra-activerecord'
  gem 'sqlite3'
end
