require 'bundler/gem_tasks'
require 'rspec/core'
require 'rspec/core/rake_task'
require 'active_support/core_ext/string/inflections'
require 'haveapi'
require 'haveapi/tasks/yard'

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = FileList['spec/**/*_spec.rb']
  spec.rspec_opts = '--require spec_helper'
end

begin
  require 'yard'

  YARD::Rake::YardocTask.new do |t|
    t.files   = ['lib/**/*.rb']
    t.options = [
      '--protected',
      '--output-dir=html_doc',
      '--files=doc/*.md',
      '--files=doc/*.html'
    ]
    t.before = proc do
      document_hooks.call
      render_doc_file('doc/json-schema.erb', 'doc/JSON-Schema.html').call
    end
  end
rescue LoadError
end
